version: '2' # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 9
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 6
  similar-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.
